/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.goodmath.cruise;

import picocli.CommandLine;

public class App {
  public static void main(String... args) {
    int exitCode = new CommandLine(new Run()).execute(args);
    System.exit(exitCode);
  }

}
