/* Generated By:JavaCC: Do not edit this line. CruiseParserConstants.java */
package org.scientopia.goodmath.cruise.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CruiseParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int ACTOR = 10;
  /** RegularExpression Id. */
  int INSTANTIATE = 11;
  /** RegularExpression Id. */
  int AS = 12;
  /** RegularExpression Id. */
  int INIT = 13;
  /** RegularExpression Id. */
  int BEHAVIOR = 14;
  /** RegularExpression Id. */
  int ON = 15;
  /** RegularExpression Id. */
  int ADOPT = 16;
  /** RegularExpression Id. */
  int SEND = 17;
  /** RegularExpression Id. */
  int TO = 18;
  /** RegularExpression Id. */
  int VARIABLEIDENT = 19;
  /** RegularExpression Id. */
  int ACTORIDENT = 20;
  /** RegularExpression Id. */
  int TYPEIDENT = 21;
  /** RegularExpression Id. */
  int TUPLETAG = 22;
  /** RegularExpression Id. */
  int BEHAVIORIDENT = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"actor\"",
    "\"instantiate\"",
    "\"as\"",
    "\"initial\"",
    "\"behavior\"",
    "\"on\"",
    "\"adopt\"",
    "\"send\"",
    "\"to\"",
    "<VARIABLEIDENT>",
    "<ACTORIDENT>",
    "<TYPEIDENT>",
    "<TUPLETAG>",
    "<BEHAVIORIDENT>",
    "<NUMBER>",
    "\"//\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 27>",
  };

}
